### ISSUE TITLE
执行mvn test后得到如下输出，请问还需要其他配置吗？

### ISSUE THREAD

**Issue by nullmax** [leehoawki/Redlock#1]
系统配置如下：
OS: 64bit Mac OS X 10.13.2 17C88
Kernel: x86_64 Darwin 17.3.0
Uptime: 6h 43m
Packages: 31
Shell: zsh 5.3
Resolution: 2560x1600
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue
Font: Monaco 12
CPU: Intel Core i5-4278U @ 2.60GHz
GPU: Intel Iris
RAM: 3885MiB / 8192MiB
maven输出：
-------------------------------------------------------------------------------
Test set: redlock.lock.RLockTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 1.005 sec <<< FAILURE!
testLockAtMultiThread2(redlock.lock.RLockTest)  Time elapsed: 0.394 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:53)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at redlock.connection.RedisSingle.eval(RedisSingle.java:67)
	at redlock.lock.RLockImpl.tryAcuqire(RLockImpl.java:145)
	at redlock.lock.RLockImpl.lock(RLockImpl.java:68)
	at redlock.lock.RLockTest$3.runTest(RLockTest.java:127)
	at net.sourceforge.groboutils.junit.v1.TestRunnable.run(TestRunnable.java:154)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset by peer (connect failed)
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:868)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:435)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)
	... 7 more
Caused by: java.net.SocketException: Connection reset by peer (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 14 more

testLockAtMultiThread3(redlock.lock.RLockTest)  Time elapsed: 0.47 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Broken pipe (Write failed)
	at redis.clients.jedis.Connection.flush(Connection.java:334)
	at redis.clients.jedis.Connection.getOne(Connection.java:320)
	at redis.clients.jedis.Jedis.getEvalResult(Jedis.java:2731)
	at redis.clients.jedis.Jedis.eval(Jedis.java:2671)
	at redis.clients.jedis.Jedis.eval(Jedis.java:2719)
	at redlock.connection.RedisSingle.eval(RedisSingle.java:68)
	at redlock.lock.RLockImpl.tryAcuqire(RLockImpl.java:157)
	at redlock.lock.RLockImpl.lock(RLockImpl.java:68)
	at redlock.lock.RLock.lock(RLock.java:22)
	at redlock.lock.RLockTest$4.runTest(RLockTest.java:146)
	at net.sourceforge.groboutils.junit.v1.TestRunnable.run(TestRunnable.java:154)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:52)
	at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:216)
	at redis.clients.jedis.Connection.flush(Connection.java:331)
	... 11 more

testUnlock(redlock.lock.RLockTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at redlock.lock.RLockTest.testUnlock(RLockTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by HaoQi-Lee** [comment]
需要启动一个redis的，testcase里我直接默认连接的本地的6379的redis=。=

**Comment by nullmax** [comment]
启动了的，默认也是6379端口的

**Comment by HaoQi-Lee** [comment]
=。=从异常来看就是连接的问题。java.net.SocketException: Connection reset by peer (connect failed) 也许可能是redis版本和我用的Jedis的兼容问题？

**Comment by nullmax** [comment]
有空我再换个jedis版本试试吧
